apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argocd
spec:
  project: project1
  source:
    repoURL: 'https://github.com/rajcsingh-git/argotest2'
    targetRevision: main
    path: test2
  destination:
    server: https://kubernetes.default.svc
    namespace: app1 
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
