apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: project1
  source:
    repoURL: https://github.com/rajcsingh-git/argo-app-of-app
    targetRevision: main  
    path: ./apps/app1
  destination:
    namespace: test6
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
