apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argocd
spec:
  project: project1
  source:
    repoURL: 'https://github.com/rajcsingh-git/argo-app-of-app'
    targetRevision: main
    path: /
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd 
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
